# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeAPP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeAPP
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket', # needed for debugging
    'RCTImage',
    # Add any other subspecs you want to use in your project
  ]
  target 'NativeAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
